FROM node:20-slim AS base
FROM base AS builder

WORKDIR /frontend
COPY package*.json package-loc.json* ./
RUN npm install
ENV NODE_ENV=production

ENV NEXT_PUBLIC_SERVER_URL=http://localhost:8000
ARG HOSTNAME

COPY . .
# RUN npm run build
EXPOSE 3000
# CMD ["npm", "run", "dev"]
# CMD ["npm", "start"]