services:
  backend:
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ..:/code
    environment:
      - DEBUG_ON_INIT=False
    command: ["python3", "-m","uvicorn", "main:app", "--reload","--host", "${APP_HOST}", "--port", "${APP_PORT}","--lifespan","on"]

#python3 -m uvicorn main:app --reload --host 0.0.0.0 --port 8001 --lifespan on
