services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - LS_LOG=trace
      - DEBUG=1
      - EAGER_SERVICE_LOADING=0
      - LOCALSTACK-CLI=1
      - ACTIVE_PRO=0
      - SERVICES=${AWS_SERVICES}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - GATEWAY_LISTEN=0.0.0.0:4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4566
      - AWS_ACCOUNT_ID=000000000000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - ../.localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network

  backend:
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ..:/code
    environment:
      - DEBUG_ON_INIT=False
    command: ["python3", "-m","uvicorn", "main:app", "--reload","--host", "${APP_HOST}", "--port", "${APP_PORT}","--lifespan","on"]

#python3 -m uvicorn main:app --reload --host 0.0.0.0 --port 8001 --lifespan on
