services:
  backend:
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${APP_DEBUG_PORT}:${APP_DEBUG_PORT}
    volumes:
      - ../server:/app
      - /app/__pycache__
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=0 # 1 for disabling "-Xfrozen_modules=off error
      - DEBUG_ON_INIT=True
    command: ["socketify","python3","-Xfrozen_modules=off", "-m", "debugpy", "--listen", "${APP_HOST}:5678", "-m","uvicorn", "main:app", "--reload","--host", "${APP_HOST}", "--port", "${APP_PORT}"]
