from enum import Enum


class UserRole(Enum):
    GENERAL_MANAGER = "GENERAL_MANAGER"
    PROJECT_MANAGER = "PROJECT_MANAGER"
    QA_MANAGER = "QA_MANAGER"
    LANGUAGE_REVIEWER = "LANGUAGE_REVIEWER"
    TRANSLATOR = "TRANSLATOR"