FROM nginx:latest

ARG APP_NAME
ARG APP_CONTAINER_NAME
ARG APP_PORT
# Copy the template Nginx config file
COPY ../nginx.conf /etc/nginx/nginx.conf.template

ENV APP_NAME=${APP_NAME}
ENV APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
ENV APP_PORT=${APP_PORT}

# Use envsubst to replace variables in the config and write it to the real Nginx config file
RUN envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

EXPOSE 80
    
CMD ["nginx", "-g", "daemon off;"]
