FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/github.com/a8m/envsubst
RUN go install github.com/a8m/envsubst/cmd/envsubst@latest

FROM prom/prometheus

COPY --from=builder /go/bin/envsubst /usr/local/bin/envsubst
COPY ../prometheus_data/entrypoint.sh /usr/local/bin/entrypoint


ENTRYPOINT [ "sh", "/usr/local/bin/entrypoint" ]
